baseURL: "https://vigilant-wilson-6bdd90.netlify.com/"
languageCode: "en-us"
title: "Kubernetes Objects Map"
theme: "kube"

params:
    twitter: "tomasz_cholewa"
    images:
        - map.png

menu:
    main:
        - name: "Objects"
          weight: -100
          url: "/objects/"
